"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 18:55:10.891309
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(length=32), nullable=False, comment='source fingerprint'),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('dialect', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.String(length=500), nullable=False),
    sa.Column('schema_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('store_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_table('context_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=True),
    sa.Column('attribute', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_context_items_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_items'))
    )
    with op.batch_alter_table('context_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_items_source_id'), ['source_id'], unique=False)

    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('semantic_model_version', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('generated', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Integer(), nullable=False),
    sa.Column('dropped_duplicate', sa.Integer(), nullable=False),
    sa.Column('flagged_similar', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_generation_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_runs'))
    )
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_runs_source_id'), ['source_id'], unique=False)

    op.create_table('metadata_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('structure_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_metadata_snapshots_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata_snapshots'))
    )
    with op.batch_alter_table('metadata_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_snapshots_source_id'), ['source_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.String(length=32), nullable=False, comment='= Rule.rule_id'),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('generation_run_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('target_entity', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('fingerprint', sa.String(length=16), nullable=False),
    sa.Column('original_fingerprint', sa.String(length=16), nullable=False, comment='fingerprint as first proposed (before edits)'),
    sa.Column('similarity_key', sa.String(length=300), nullable=False),
    sa.Column('similar_to_rule_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], name=op.f('fk_rules_generation_run_id_generation_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['similar_to_rule_id'], ['rules.id'], name=op.f('fk_rules_similar_to_rule_id_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_rules_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    sa.UniqueConstraint('source_id', 'fingerprint', name=op.f('uq_rules_source_id'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_original_fingerprint'), ['original_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_similarity_key'), ['similarity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_rules_source_status', ['source_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_target_entity'), ['target_entity'], unique=False)

    op.create_table('semantic_model_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['metadata_snapshots.id'], name=op.f('fk_semantic_model_versions_snapshot_id_metadata_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_semantic_model_versions_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_model_versions')),
    sa.UniqueConstraint('source_id', 'version', name=op.f('uq_semantic_model_versions_source_id'))
    )
    with op.batch_alter_table('semantic_model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_model_versions_source_id'), ['source_id'], unique=False)

    op.create_table('rule_reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_reviews_rule_id_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_reviews'))
    )
    with op.batch_alter_table('rule_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_reviews_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_reviews_rule_id'))

    op.drop_table('rule_reviews')
    with op.batch_alter_table('semantic_model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_model_versions_source_id'))

    op.drop_table('semantic_model_versions')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_target_entity'))
        batch_op.drop_index('ix_rules_source_status')
        batch_op.drop_index(batch_op.f('ix_rules_source_id'))
        batch_op.drop_index(batch_op.f('ix_rules_similarity_key'))
        batch_op.drop_index(batch_op.f('ix_rules_original_fingerprint'))

    op.drop_table('rules')
    with op.batch_alter_table('metadata_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_snapshots_source_id'))

    op.drop_table('metadata_snapshots')
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_runs_source_id'))

    op.drop_table('generation_runs')
    with op.batch_alter_table('context_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_items_source_id'))

    op.drop_table('context_items')
    op.drop_table('sources')
    # ### end Alembic commands ###
