"""review reason code

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 16:17:04.907925
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_code', sa.String(length=30), nullable=True, comment='wrong | not_relevant | too_strict | ...'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_reviews', schema=None) as batch_op:
        batch_op.drop_column('reason_code')

    # ### end Alembic commands ###
